# Generated by Django 3.1.7 on 2021-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMasterApp', '0002_ticket_ticketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketid',
            name='ticket_set',
            field=models.ManyToManyField(blank=True, to='GameMasterApp.Ticket'),
        ),
    ]
