# Generated by Django 3.1.7 on 2021-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMasterApp', '0003_auto_20210405_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('winners', models.CharField(blank=True, default='[]', max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
