# Generated by Django 3.1.7 on 2021-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameMasterApp', '0004_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketid',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
