import Vue from 'vue'
import Vuex from 'vuex'
import {compareDate} from "src/common/utils";

// import example from './module-example'

Vue.use(Vuex)
/*
 * If not building with SSR mode, you can
 * directly export the Store instantiation;
 *
 * The function below can be async too; either use
 * async/await or return a Promise which resolves
 * with the Store instance.
 */
export default function (/* { ssrContext } */) {
  const Store = new Vuex.Store({
    modules: {},
    state: {
      selectionState:{},
      lotteryTimings:[ new Date(1617878700000) ,new Date(1617879600000) ],
      nextLottery:null,
      results: {'A':'', 'B':'','C': '','D': '','E' :'','F': '','G': '','H': '','I': '','J': ''},
      price : 10,
      inputs: {
        A: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
        },
        B: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,

        },
        C: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        D: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        E: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null        },
        F: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        G: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        H: {
         "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        I: {
        "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        J: {
         "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
      },
      selectedSets:{A:false,B:false,C:false,D:false,E:false,F:false,G:false,H:false,I:false,J:false},
      setPoints:{A:2,B:2,C:2,D:2,E:2,F:2,G:2,H:2,I:2,J:2},
      previousLottery:null
    },
    mutations: {
      push_ticket(state, ticket) {
        state.selectionState[ticket['ticket']] = ticket['quantity']
      },
      set_lottery_timings(state,timings) {
        state.lotteryTimings = timings
      },
      set_next_lottery(state) {
        for (var i = 0; i < state.lotteryTimings.length; i++) {
            if(compareDate(new Date() , state.lotteryTimings[i]) > 0) {

            }
            else{
              console.log("lottery after")
              console.log("setting next lottery as"+state.lotteryTimings[i])
              state.nextLottery = state.lotteryTimings[i];
              break;
            }
        }
      },
      set_previous_lottery(state) {
        for (var i = 0; i < state.lotteryTimings.length; i++) {
            if(compareDate(new Date() , state.lotteryTimings[i]) > 0) {

            }
            else{
              console.log("setting previous lottery")
              state.previousLottery = state.lotteryTimings[i-1];
              break;
            }
        }
      },
      change_selected_sets(state,selectionState){
        state.selectedSets.A=selectionState.A;
        state.selectedSets.B=selectionState.B;
        state.selectedSets.C=selectionState.C;
        state.selectedSets.D=selectionState.D;
        state.selectedSets.E=selectionState.E;
        state.selectedSets.F=selectionState.F;
        state.selectedSets.G=selectionState.G;
        state.selectedSets.H=selectionState.H;
        state.selectedSets.I=selectionState.I;
        state.selectedSets.J=selectionState.J;
      }
    },
    actions: {
      push_ticket ({ commit }, ticket) {
          commit('push_ticket', ticket)
       },
      set_lottery_timings({commit},timings) {
        console.log("setting lottery timings")
        commit('set_lottery_timings',timings)
      },
      set_next_lottery({commit}) {
        console.log("setting next lottery")
        commit('set_next_lottery')
      },
      set_previous_lottery({commit}) {
        console.log("setting previous lottery")
        commit('set_previous_lottery')
      },
      change_selected_sets({commit},selected) {
        commit('change_selected_sets',selected)
      }
    },

    getters:{
      get_selected: state => {
        return state.selectionState
      },
      get_next_lottery: state => {
        return state.nextLottery
      },
      get_last_lottery_time:state => {

      }
    },

    // enable strict mode (adds overhead!)
    // for dev mode only
    strict: process.env.DEBUGGING
  })

  return Store
}
