<template>
  <div class="">
    <div class="row">
      <div class="col ">
        <div class="row " v-for="i in 10" :key="i" >
        <div class="" v-for="n in 10" :key="n">
          <q-card class="q-ml-sm q-mr-sm text-center" flat>
            <div style=""> {{ i*10+n-10}} </div>
            <input style="height: 20px;width: 40px" v-model="inputs[set][i*10+n-10]" @input="add_input(i*10+n-10)"/>
          </q-card>
          </div>
        </div>
      </div>
      <div class="col-2 bg-light-green " style="" >{{$store.state.selectionState}}</div>
    </div>

  </div>
</template>
<script>
export default {
  name: "SelectionTable",
  props: ['set'],
  data() {
    return {
      inputs: {
        A: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null

        },
        B: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null

        },
        C: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        D: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        E: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null        },
        F: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        G: {
          "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        H: {
         "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        I: {
        "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
        J: {
         "0": null,
          "1": null,
          "2": null,
          "3": null,
          "4": null,
          "5": null,
          "6": null,
          "7": null,
          "8": null,
          "9": null,
          "10":null,
          "11":null,
          "12":null,
          "13":null,
          "14":null,
          "15":null,
          "16":null,
          "17":null,
          "18":null,
          "19":null,
          "20":null,
          "21":null,
          "22":null,
          "23":null,
          "24":null,
          "25":null,
          "26":null,
          "27":null,
          "28":null,
          "29":null,
          "30":null,
          "31":null,
          "32":null,
          "33":null,
          "34":null,
          "35":null,
          "36":null,
          "37":null,
          "38":null,
          "39":null,
          "40":null,
          "41":null,
          "42":null,
          "43":null,
          "44":null,
          "45":null,
          "46":null,
          "47":null,
          "48":null,
          "49":null,
          "50":null,
          "51":null,
          "52":null,
          "53":null,
          "54":null,
          "55":null,
          "56":null,
          "57":null,
          "58":null,
          "59":null,
          "60":null,
          "61":null,
          "62":null,
          "63":null,
          "64":null,
          "65":null,
          "66":null,
          "67":null,
          "68":null,
          "69":null,
          "70":null,
          "71":null,
          "72":null,
          "73":null,
          "74":null,
          "75":null,
          "76":null,
          "77":null,
          "78":null,
          "79":null,
          "80":null,
          "81":null,
          "82":null,
          "83":null,
          "84":null,
          "85":null,
          "86":null,
          "87":null,
          "88":null,
          "89":null,
          "90":null,
          "91":null,
          "92":null,
          "93":null,
          "94":null,
          "95":null,
          "96":null,
          "97":null,
          "98":null,
          "99": null,
          "100":null
        },
      }
    }
  },
  methods: {
    add_input:function (n){
      console.log(this.set+n +' '+ this.inputs[this.set][n])
      this.$store.dispatch('push_ticket',{ticket:this.set+(n),quantity:{quantity:parseInt(this.inputs[this.set][n]) , price:this.$store.state.price}})
      console.log(this.$store.state.selectionState);
    }
  },

}
</script>

<style scoped>

</style>
